version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test
      - run:
          name: Build binary
          command: go build
      - save_cache:
          key: go_build_$CIRCLE_SHA1
          paths: gridgo
  smoke-tests:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - run:
          name: Install inspec
          command: |
            gem install --no-document inspec
            gem install --no-document inspec-bin
      - restore_cache:
          key: go_build_$CIRCLE_SHA1
      - run:
          name: Run smoke tests
          command: echo yes | inspec exec tests/smoke/gridgo.rb

workflows:
  version: 2
  dev-master:
    jobs:
      - build
      - smoke-tests:
          requires:
            - build
